apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common-nginx-server
  namespace: argocd
spec:
  generators:
      - clusters: {}
  template:
    metadata:
      name: '{{name}}-nginx-server'
    spec:
      project: default
      source:
        repoURL: https://https://3000-port-k4ohnzuvumgobajj.labs.kodekloud.com/kk-org/gitops-argocd-capa
        targetRevision: HEAD
        path: ./nginx-app
      destination:
        server: '{{server}}'
        namespace: nginx-server
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
