apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: templated-workflow-
  namespace: argo
spec:
  entrypoint: cowsay
  workflowTemplateRef:
    name: cowsay-template
  arguments:
    parameters:
    - name: message
      value: "Hello from a WorkflowTemplate!"
